name: build
on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:${{ matrix.distribution }}
    strategy:
      matrix:
       distribution: [bookworm, trixie]
    steps:
      - name: install aux deps
        run: apt update && apt -y --no-install-recommends install git ca-certificates curl gpg wget
      - name: add pgdg pkg repo
        run: >
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt ${{ matrix.distribution }}-pgdg main" >> /etc/apt/sources.list.d/pgdg.list &&
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
      - name: add yeti pkg repo
        run: >
          echo "deb [arch=amd64] https://deb.yeti-switch.org/debian/1.14 ${{ matrix.distribution }} main" > /etc/apt/sources.list.d/yeti.list &&
          wget https://deb.yeti-switch.org/yeti.gpg -O /etc/apt/trusted.gpg.d/yeti-key.asc
      - run: apt update

      - name: clone repo
        uses: actions/checkout@v3

      - name: install build deps
        run: apt -y --no-install-recommends build-dep .
      - name: build
        run: make deb

      - uses: yeti-switch/upload-debian-pkg-action@v2
        with:
          pkgs: '../*.deb'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          s3_access_key_id: ${{ secrets.DEB_AWS_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.DEB_AWS_SECRET_ACCESS_KEY }}
          s3_endpoint_url: ${{ secrets.DEB_AWS_ENDPOINT }}
          s3_codename: ${{ matrix.distribution }}
          s3_prefix: '1.14'
        if: startsWith(github.ref, 'refs/tags/v')
