#!/usr/bin/python
from xmlrpclib import *
from sys import *

l = len(argv)

def ss(v,keys):
	#print "ss: v:{} keys:{}".format(v, keys)
	w = 0
	for i,k in enumerate(keys):
		v = v[k]
		if i+1 == len(keys):
			if type(v) is (int or float or long):
				#print "integer: {} = {} ".format(".".join(keys),v)
				w += v;
			else:
				print "invalid key type {} for key '{}'".format(type(v),key)
		else:
			if type(v) is list:
				#print "list"
				for l in v: 
					w += ss(l,keys[i+1:])
				break
	return w


if l < 3 or argv[1] == '--help':
	print "usage: %s uri counter1 [counter2, ...] " % argv[0]
	exit(1)

try:
	s = ServerProxy(argv[1])
	data=s.di('yeti','getStats')
	q = 0
	for key in argv[2:]:
		kk = key.split('.')
		q+=ss(data[kk[0]],kk[1:])
	print q
except Fault as err:
	print "Fault code: %d" % err.faultCode
	print "Fault string: %s" % err.faultString
except BaseException as err:
	print "Err: %s" % err
